### ISSUE TITLE
Update payload-gen-dna-seq-qc tool

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/data-processing-utility-tools#116]
Details in https://wiki.oicr.on.ca/display/icgcargotech/SONG+schema+adjustments+in+the+context+of+mapping+to+file+repo+facet#SONGschemaadjustmentsinthecontextofmappingtofilerepofacet-Payloadsmigrationtasks

Also need to add support to pass on `info.origin` from input analysis to generated payload

**Comment by junjun-zhang** [comment]
addressed by #123
