### ISSUE TITLE
Update payload-gen-read-group-ubam

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/data-processing-utility-tools#117]
Details in https://wiki.oicr.on.ca/display/icgcargotech/SONG+schema+adjustments+in+the+context+of+mapping+to+file+repo+facet#SONGschemaadjustmentsinthecontextofmappingtofilerepofacet-Payloadsmigrationtasks

**Comment by junjun-zhang** [comment]
I don't think we still use this tool
