### ISSUE TITLE
Update payload-gen-variant-calling tool

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/data-processing-utility-tools#118]
Details in https://wiki.oicr.on.ca/display/icgcargotech/SONG+schema+adjustments+in+the+context+of+mapping+to+file+repo+facet#SONGschemaadjustmentsinthecontextofmappingtofilerepofacet-Payloadsmigrationtasks

**Comment by junjun-zhang** [comment]
it's good time to address this one as well: https://github.com/icgc-argo/workflow-roadmap/issues/125

**Comment by junjun-zhang** [comment]
addressed by #119
