### ISSUE TITLE
Update the workflow song payload generation step to include run_name

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/data-processing-utility-tools#72]
`workflow.run_name` and `workflow.session_id` variables are available and should be assigned to the song `run_id` and `session_id` fields

**Comment by lindaxiang** [comment]
Addressed by https://github.com/icgc-argo/data-processing-utility-tools/pull/78, https://github.com/icgc-argo/data-processing-utility-tools/pull/77, https://github.com/icgc-argo/data-processing-utility-tools/pull/76
