### ISSUE TITLE
🐛 typo 'Qualitiy Control Metrics' in 'payload-gen-variant-calling'

### ISSUE THREAD

**Issue by junjun-zhang** [icgc-argo/data-processing-utility-tools#73]
https://github.com/icgc-argo/data-processing-utility-tools/blob/payload-gen-variant-calling.0.2.0.0/tools/payload-gen-variant-calling/payload-gen-variant-calling.py#L45-L48

`Qualitiy Control Metrics` => `Quality Control Metrics`

**Comment by lindaxiang** [comment]
Addressed by https://github.com/icgc-argo/data-processing-utility-tools/pull/74
